permit persist :wheel

permit nopass gnuplex as root cmd /sbin/reboot
permit nopass gnuplex as root cmd /sbin/poweroff
permit nopass gnuplex as root cmd reboot
permit nopass gnuplex as root cmd poweroff
